### PR TITLE
AndroidLowLevelDetector: Add Chinese(Traditional) Translate

### PR DESCRIPTION
**Pull request by bluehomewu**
Signed-off-by: Edward Wu <bluehome.wu@gmail.com>

Please fix Chinese(Traditional) translator name (My name) on [Line 193 ~ Line 195](https://github.com/bluehomewu/AndroidLowLevelDetector/commit/d7af5fb8ad760b7b4bff39cfd00748d79d9b4106#diff-6986b2eda15d624655c5962c57e12dea676b6aaa06bf31a5ced02f38141f47d1R193-R195)

I'm not sure how would you modify it, so I only left my name, didn't modified strings name.
Thank you!

### CODE REVIEW

**Comment by imknown** [comment]
Hi, thank you very much for your Pull Request. 😸
I have reviewed this PR, and all are OK.

But after checking this, I find something wrong in `zh-rCH`, 
such as `\u0020`, which should be used for Indo-European languages (English, French, Etc.). 
So no need to add it for CJK languages, I think.
I have corrected them in https://github.com/imknown/AndroidLowLevelDetector/commit/e0cb44802ca84d672f4f33eb93a93e949efeb862.

So, I will merge this PR and, likewise, I will correct them later myself.
Is that OK?

By the way, translator info format can be like:
```
    <string name="translation_language_and_translator">繁體中文（臺灣），翻譯：bluehomewu</string>
    <string name="translator_website"><HERE YOUR WEBSITE></string>
    <string name="translator_more_info">https://github.com/bluehomewu</string>
```

Thank you again for your translation. 😺

**Comment by bluehomewu** [comment]
> Hi, thank you very much for your Pull Request. 😸 I have reviewed this PR, and all are OK.
> 
> But after checking this, I find something wrong in `zh-rCH`, such as `\u0020`, which should be used for Indo-European languages (English, French, Etc.). So no need to add it for CJK languages, I think. I have corrected them in [a4bbbae](https://github.com/imknown/AndroidLowLevelDetector/commit/a4bbbaefa1e37d96acce69e7335513bdf9afaaca).
> 
> So, I will merge this PR and, likewise, I will correct them later myself. Is that OK?
> 
> By the way, translator info format can be like:
> 
> ```
>     <string name="translation_language_and_translator">繁體中文（臺灣），翻譯：bluehomewu</string>
>     <string name="translator_website"><HERE YOUR WEBSITE></string>
>     <string name="translator_more_info">https://github.com/bluehomewu</string>
> ```
> 
> Thank you again for your translation. 😺

I don't have a personal website, so second one please point to my GitHub page too. Thanks.

**Comment by imknown** [comment]
Merged and modified [here](https://github.com/imknown/AndroidLowLevelDetector/blob/develop/app/src/main/res/values-zh-rTW/strings.xml#L194-L196).

**Comment by bluehomewu** [comment]
> Merged and modified [here](https://github.com/imknown/AndroidLowLevelDetector/blob/develop/app/src/main/res/values-zh-rTW/strings.xml#L194-L196).

Thanks for help.

**Pull request merged**
